<?php
/**
 * @var $block \Yotpo\Loyalty\Block\Snippet
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer|null
 */
?>
<?php if (!$block->shouldLoadSnippet()) {
    return;
} ?>

<?php
$scriptContent = "
(function() {
    document.addEventListener('DOMContentLoaded', function() {
        try {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', '" . $block->getSnippetLoaderUrl() . "' + '?timestamp=' + new Date().getTime(), true);
            xhr.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
            xhr.setRequestHeader('Pragma', 'no-cache');
            xhr.setRequestHeader('Expires', '0');

            xhr.onreadystatechange = function() {
                if (xhr.readyState === 4) {
                    if (xhr.status >= 200 && xhr.status < 300) {
                        var response;
                        try {
                            response = JSON.parse(JSON.parse(xhr.responseText));
                        } catch (e) {
                            throw new Error('Failed to parse JSON response: ' + e.message);
                        }

                        if (!response.error) {
                            if (
                              typeof require !== 'undefined' && typeof requirejs !== 'undefined' &&
                              response.invalidate_customer_cart
                            ) {
                                require(['Magento_Customer/js/customer-data'], function(customerData) {
                                    customerData.invalidate(['cart']);
                                });
                            }

                            if (response.snippet) {
                                var snippet = document.createElement('div');
                                snippet.innerHTML = response.snippet;
                                document.body.appendChild(snippet);
                            }

                            if (response.scripts && Array.isArray(response.scripts)) {
                                response.scripts.forEach(function(scriptObj) {
                                    if (scriptObj.src) {
                                        var script = document.createElement('script');
                                        script.type = 'text/javascript';
                                        script.async = !!scriptObj.async;
                                        script.src = scriptObj.src;
                                        document.head.appendChild(script);
                                    }
                                });
                            }
                        } else {
                            throw response || 'Unknown error occurred';
                        }
                    } else {
                        throw new Error('HTTP error occurred: ' + xhr.status + ' ' + xhr.statusText + ' - ' + xhr.responseText);
                    }
                }
            };

            xhr.onerror = function() {
                throw new Error('Request failed due to a network error');
            };

            xhr.send();
        } catch (e) {
            " . ($block->isDebugMode() ? "console.error(e);" : "console.error('Yotpo Loyalty Error - Enable debug mode in order to see more details...');") . "
        }
    });
})();
";
?>

<!-- Yotpo Loyalty - Snippet Loader -->
<?php if (isset($secureRenderer)): ?>
    <?= $secureRenderer->renderTag('script', ['data-yotpo-loyalty' => $block->getModuleVersion()], $scriptContent, false) ?>
<?php else: /* NOTE: Backwards compatibility */ ?>
    <script data-yotpo-loyalty="<?= $escaper->escapeHtml($block->getModuleVersion()) ?>">
        <?= $scriptContent ?>
    </script>
<?php endif; ?>
<!--/ Yotpo Loyalty - Snippet Loader -->
