<?php
/**
 * @var $block \Yotpo\Loyalty\Block\Snippet
 */
?>
<?php if (!$block->isEnabled()) {
    return;
} ?>
<!-- Yotpo Loyalty - Snippet Loader -->
<script>
    (function  () {
        require([
            "jquery",
            'mage/storage'
        ],function($, storage) {
            $(document).ready(function() {
                storage.get(
                    '/rest/V1/swell/session/snippet'
                ).done(function (response) {
                    if(response){
                        $("body").append(response);
                    }
                }).fail(function (response) {
                    <?php if ($block->isDebugMode()): ?>
                        console.error(response);
                    <?php else: ?>
                        console.error("Yotpo Error - Enable debug mode in order to see more details...");
                    <?php endif; ?>
                });
            });
        });
    })();
</script>
<!--/ Yotpo Loyalty - Snippet Loader -->
