<?php

use Yotpo\Loyalty\Helper\Data as YotpoLoyaltyHelper;

/**
 * @var $block \Yotpo\Loyalty\Block\UrlCouponCodeJs
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer|null
 */
?>
<?php if (!$block->isEnabled() || !($couponCodeUrl = $block->getUrlCouponCodeUrl())) {
    return;
} ?>

<?php
$scriptContent = "
localStorage.setItem('" . $escaper->escapeJs(YotpoLoyaltyHelper::COUPON_CODE_QUERY_PARAM) . "_url', '" . $escaper->escapeJs($couponCodeUrl) . "');
";
?>

<!-- Yotpo Loyalty - Frontend URL coupon processor -->
<?php if (isset($secureRenderer)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', ['data-yotpo-loyalty' => $block->getModuleVersion()], $scriptContent, false) ?>
<?php else: /* NOTE: Backwards compatibility */ ?>
    <script data-yotpo-loyalty="<?= $escaper->escapeHtmlAttr($block->getModuleVersion()) ?>">
        <?= /* @noEscape */ $scriptContent ?>
    </script>
<?php endif; ?>
<!--/ Yotpo Loyalty - Frontend URL coupon processor -->
