<?php

use Yotpo\Loyalty\Helper\Data as YotpoLoyaltyHelper;

/**
 * @var $block \Yotpo\Loyalty\Block\UrlCouponCodeJs
 */
?>
<?php if (!$block->isEnabled()) {
    return;
} ?>
<!-- Yotpo Loyalty - Frontend URL coupon processor -->
<script data-yotpo-loyalty="<?= /* @noEscape */ $block->getModuleVersion() ?>">
    (function() {
        var yotpoLoyaltyCouponCodeUrl = localStorage.getItem('<?= $block->escapeHtmlAttr(YotpoLoyaltyHelper::COUPON_CODE_QUERY_PARAM) ?>_url');
        if (!yotpoLoyaltyCouponCodeUrl) {
            return;
        }

        document.addEventListener("DOMContentLoaded", function() {
            try {
                var xhr = new XMLHttpRequest();
                xhr.open('GET', yotpoLoyaltyCouponCodeUrl + '&timestamp=' + new Date().getTime(), true);
                xhr.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
                xhr.setRequestHeader('Pragma', 'no-cache');
                xhr.setRequestHeader('Expires', '0');

                xhr.onreadystatechange = function() {
                    if (xhr.readyState === 4) {
                        if (xhr.status >= 200 && xhr.status < 300) {
                            var response;
                            try {
                                response = JSON.parse(xhr.responseText);
                            } catch (e) {
                                throw new Error('Failed to parse JSON response: ' + e.message);
                            }

                            if (response.error) {
                                throw response || 'Unknown error occurred';
                            } else if (response.success) {
                                localStorage.removeItem('<?= $block->escapeHtmlAttr(YotpoLoyaltyHelper::COUPON_CODE_QUERY_PARAM) ?>_url');
                            }
                        } else {
                            throw new Error('HTTP error occurred: ' + xhr.status + ' ' + xhr.statusText + ' - ' + xhr.responseText);
                        }
                    }
                };

                xhr.onerror = function() {
                    throw new Error('Request failed due to a network error');
                };

                xhr.send();
            } catch (e) {
                <?php if ($block->isDebugMode()): ?>
                    console.error(e);
                <?php else: ?>
                    console.error("Yotpo Loyalty Error - Enable debug mode in order to see more details...");
                <?php endif; ?>
            }
        });
    })();
</script>
<!--/ Yotpo Loyalty - Frontend URL coupon processor -->
